### ISSUE TITLE
923 error after 

### ISSUE THREAD

**Issue by iPsych** [kercre123/wire-pod#104]
Using Vector with OSKR v 1.7.x, I followed the wiki instruction.

`"Set up OSKR/dev bot", enter the bot's IP address, upload the key, then press set up.`

It seems successfully replaced vic-cloud and other files.

However whenever I finish the authentication, the Vector go to '**923**' state.

What currently did : 

-made the hostname same to escapepod
-re-installed the Vector to OSKR .ota released by DDL (1.7.6, since 1.8.0.xxx did not work. It was latest.ota)
-try to authenticate outside OSKR, no luck.

What should I do? Currently working on Ubuntu-installed laptop. (18.04 LTS)

**Comment by kercre123** [comment]
When you try to authenticate, does wire-pod show any additional logs? And may you get the logs from the robot? With OSKR, you can get the bot's `/var/log/messages` file directly via SSH/SCP.
