### ISSUE TITLE
Failing to activate BOT

### ISSUE THREAD

**Issue by Siman007** [kercre123/wire-pod#105]
Hi - I'm running on RP4, I get to the point of connecting to my BOT - it pairs, then shows the activate button, clicking on it and after 15 secs it says 'Error logging in. The bot is likely unable to communicate with your wire-pod instance... '

BOT is v1 on v2.0.1.6076

I have followed all the instructions and configured wire-pod correctly.

Tried a complete rebuild of the PI and tried two different wifi networks etc.

VectorX RELEASE_11

Any ideas?

![IMG_3617](https://user-images.githubusercontent.com/28743769/223861717-91bc26de-2e03-4007-a01e-3acff1b5c350.jpg)

**Comment by kercre123** [comment]
Have you configuerd wire-pod as directed in the wiki or are you using a pre-setup Pi image? May you send over the response from the following commands (on the Pi):

`systemctl status wire-pod`
`systemctl status avahi-daemon`

**Comment by scamfield** [comment]
I encountered the same error on Debian, and I can confirm that the problem was related to avahi-daemon not starting. However, the root cause of my issue was that dbus was not started. Once I started dbus, I was able to start avahi-daemon and everything began working correctly.

**Comment by Jayman340** [comment]
im getting the same issue using win 10 method

**Comment by silentswordau** [comment]
I am getting the same error message and I have done everything exactly as it was written, I have even watched youtube videos to make sure I am doing everything correctly...  I am also running windows 10 and I have no idea what dbus?  I am just a mum trying to get this thing going for her 8 year old and have no tech skills.  can someone please help me?
