### ISSUE TITLE
armv71 WARN

### ISSUE THREAD

**Issue by Whats-name** [kercre123/wire-pod#109]
Installing Wire-Pod on Pi 3 B+ and I get the following when trying to run the setup  via `sudo STT=vosk ./setup.sh`

```
Debian-based Linux confirmed.
armv7l WARN: The Coqui and VOSK bindings are broken for this platform at the moment, so please choose Picovoice when the script asks.
```
I've separately installed VOSK using `pip3 install vosk` but it makes no difference, still the same error when I run `sudo STT=vosk ./setup.sh`

I'm happy to go with Picovoice if needed, but have no idea how...

**Comment by kercre123** [comment]
Run it like `sudo ./setup.sh`, without the `STT=vosk`, then you will be given the option to choose Picovoice. Though, I recommend doing a reinstall of Raspbian with the 64-bit version rather than 32-bit instead.

**Comment by Whats-name** [comment]
Thank you, I will try that shortly when the current process has finished.

TBH I have never considered the 64 v 32, the Pi has been running for quite some time with various things I have on it, so ideally don't want to do a fresh install.

**Comment by Whats-name** [comment]
@kercre123 same issue with `sudo ./setup.sh` where no options are presented, just:

```
Debian-based Linux confirmed.
armv7l WARN: The Coqui and VOSK bindings are broken for this platform at the moment, so please choose Picovoice when the script asks.
```

**Comment by kercre123** [comment]
Just pushed a fix, try `git pull` then try `sudo ./setup.sh` again.
