### ISSUE TITLE
Error initializing bluetooth on the device running wire-pod. Use the following site on any machine with Bluetooth for setup

### ISSUE THREAD

**Issue by F4310** [kercre123/wire-pod#120]
I trie on two computers and  with a android smartphone. Any idea? 
My hostname alredy is scapepod.
![image](https://user-images.githubusercontent.com/4128274/229105862-5fc0afe7-725b-4d46-8afe-691e5a7c4773.png)

**Comment by f0rky** [comment]
I'm in the same boat, confirmed the host of wire-pod is escapepod
avahi is running on the host and is named escapepod.local
ping escapepod.local resolves to the correct IP
navigating to http://escapepod.local brings up the web menu

The instructions are pretty lite in terms of troubleshooting at this step, does anyone know what else could be checked?

**Comment by F4310** [comment]
I solved the issue, try: 

Before start i did a reset on it
1 - I installed Xubuntu and followed installation guide
2 - Host name changed to escapepod
3 - Vector and server connected on the same network
