### ISSUE TITLE
Cheaper alternative to Rasberry pi?

### ISSUE THREAD

**Issue by Jetpackjules** [kercre123/wire-pod#122]
GPT 3-5 or GPT3?

I am asking because 3-5 can produce much better conversational results, and costs 10x less than GPT 3

**Comment by Sovenger** [comment]
https://github.com/kercre123/wire-pod/blob/7117ad9042ab2545b1eeef34e314a69335a7a1fa/chipper/pkg/wirepod/preqs/knowledgegraph.go#L77

**Comment by Jetpackjules** [comment]
Thanks! While I have you, what would you reccomend as a cheaper alternative to the rasberry pi 4 if there is one?

**Comment by kercre123** [comment]
wire-pod works well on an Orange Pi 4 LTS.

**Comment by bliteknight** [comment]
> Thanks! While I have you, what would you reccomend as a cheaper alternative to the rasberry pi 4 if there is one?

I sell a cheaper alternative, using an Android TV box (T95mini)
https://techshop82.com/shop/wire-pod-server/
