### ISSUE TITLE
Chipper 

### ISSUE THREAD

**Issue by mdinolfo123** [kercre123/wire-pod#131]
I updated today, and ran "sudo ./chipper/start.sh"

This happened:

"# github.com/kercre123/chipper/pkg/wirepod/config-ws
pkg/wirepod/config-ws/webserver.go:328:2: syntax error: unexpected else, expecting }"

It won't run.

**Comment by SummerSigh** [comment]
Same here

**Comment by SummerSigh** [comment]
I fixed the issue. In webserver.go the DownloadVoskModel function should look like the following:

```
func DownloadVoskModel(language string) {
	filename := "vosk-model-small-"
	if language == "en-US" {
		filename = filename + "en-us-0.15.zip"
	} else if language == "it-IT" {
		filename = filename + "it-0.22.zip"
	} else if language == "es-ES" {
		filename = filename + "es-0.42.zip"
	} else if language == "fr-FR" {
		filename = filename + "fr-0.22.zip"
	} else if language == "de-DE" {
		filename = filename + "de-0.15.zip"
	} else if language == "pt-BR" {
		filename = filename + "pt-0.3.zip"
	} else {
		logger.Println("Language not valid? " + language)
		return
	}
	os.MkdirAll("../vosk", 0755)
	url := "https://alphacephei.com/vosk/models/" + filename
	filepath := os.TempDir() + "/" + filename
	destpath := "../vosk/models/" + language + "/"
	DownloadFile(url, filepath)
	UnzipFile(filepath, destpath)
	os.Rename(destpath+strings.TrimSuffix(filename, ".zip"), destpath+"model")
	vars.DownloadedVoskModels = append(vars.DownloadedVoskModels, language)
	DownloadStatus = "Reloading voice processor"
	vars.APIConfig.STT.Language = language
	vars.APIConfig.PastInitialSetup = true
	vars.WriteConfigToDisk()
	processreqs.ReloadVosk()
	logger.Println("Reloaded voice processor successfully")
	DownloadStatus = "success"
}
```

**Comment by SummerSigh** [comment]
Was simply the else statement for if the "Language not valid?" not being formatted properly

**Comment by mdinolfo123** [comment]
Unfortunately, I can only open webserver.go as "read only".

**Comment by kercre123** [comment]
May someone open up a pull request? I won't be at a computer for a while.

**Comment by mdinolfo123** [comment]
I never did a pull request. Wish I could help. Instead, I'll wait.

**Comment by SummerSigh** [comment]
I got it

**Comment by mdinolfo123** [comment]
Thank you.

**Comment by SummerSigh** [comment]
@mdinolfo123 the repo has just been updated. If the error goes away could you close the issue?

**Comment by mdinolfo123** [comment]
@SummerSigh When it gets to "wire-pod started successfully!" it's frozen, I think. No voice commands. I can access localhost:8080 and play with that just fine. 

Do you have voice commands?

**Comment by SummerSigh** [comment]
I haven't gotten bluetooth working 100% just yet

**Comment by SummerSigh** [comment]
> @SummerSigh When it gets to "wire-pod started successfully!" it's frozen, I think. No voice commands. I can access localhost:8080 and play with that just fine.
> 
> Do you have voice commands?

Could you close this and make a new issue then?
