### ISSUE TITLE
setup.sh fails

### ISSUE THREAD

**Issue by Calimerorulez** [kercre123/wire-pod#136]
Hi,

I've just tried to run the setup script as sudo user, and the following error is thrown on line 200:

`./setup.sh: line 200: /usr/local/go/bin/go: No such file or directory`

Go does exists on that location, so I do not understand why it errors out. 

`-rwxr-xr-x 1 root root 14518078 Dec  1 19:15 /usr/local/go/bin/go`

**Comment by F4310** [comment]
Hello.
Have you did all steps from the guide ?
https://github.com/kercre123/wire-pod/wiki/Installation

Step 1 

cd ~
git clone https://github.com/kercre123/wire-pod

Step 2
cd ~/wire-pod
sudo STT=vosk ./setup.sh

Step 3
sudo ./chipper/start.sh

**Comment by F4310** [comment]
Hello.
Have you did all steps from the guide ?
https://github.com/kercre123/wire-pod/wiki/Installation

Step 1

cd ~
git clone https://github.com/kercre123/wire-pod

Step 2
cd ~/wire-pod
sudo STT=vosk ./setup.sh

Step 3
sudo ./chipper/start.sh

**Comment by redbullmarky** [comment]
I can confirm I also had this issue on an RPi 4. The file was there but still the message appeared.

As an accidental workaround, I followed the instructions to set up wire-prod-pod image and once that gave me a somewhat working setup, I followed the main wirepod instructions on the same image. That worked without a hitch.

**Comment by wolfgangh** [comment]
Same problem here on a RPI 4. 
Did all the steps described in the [installation guide for Linux](https://github.com/kercre123/wire-pod/wiki/Installation#guide-1-linux)
`sudo STT=vosk ./setup.sh` exited with the same error as mentioned above: 
` Vosk config
Getting VOSK assets
vosk-linux-aarch64- 100%[===================>]   2.26M  1.69MB/s    in 1.3s
Archive:  vosk-linux-aarch64-0.3.45.zip
   creating: vosk-linux-aarch64-0.3.45/
  inflating: vosk-linux-aarch64-0.3.45/vosk_api.h
  inflating: vosk-linux-aarch64-0.3.45/libvosk.so
./setup.sh: line 200: /usr/local/go/bin/go: No such file or directory`

**Comment by kercre123** [comment]
It seems that the new 32-bit raspi os images have a 64-bit kernel, just with 32-bit userspace applications/libs... which is troubling as setup.sh determines the cpu architecture with the system's uname, which contains the kernel arch. Seems like I will need to implement a new way of determing this

**Comment by LordJuice1** [comment]
I'm having the same problem as described. Running 64 bit on my Pi4. Even if I pick a different STT, I receive a similar error.

Is there any update on this? Things I can try?

**Comment by RFC1795** [comment]
Hitting the same issue:

Getting VOSK assets
vosk-linux-aarch64-0.3.45.zi 100%[===========================================>]   2.26M  9.01MB/s    in 0.3s    
Archive:  vosk-linux-aarch64-0.3.45.zip
   creating: vosk-linux-aarch64-0.3.45/
  inflating: vosk-linux-aarch64-0.3.45/vosk_api.h  
  inflating: vosk-linux-aarch64-0.3.45/libvosk.so  
./setup.sh: line 201: /usr/local/go/bin/go: No such file or directory
pi@raspberrypi:~/wire-pod$

**Comment by Trashami** [comment]
same problem here. Is there any workarounds yet?

**Comment by RamblingGeekUK** [comment]
64 Bit of Raspberry Pi OS ? I have the same issue, I have been installing GO manually.

**Comment by LordJuice1** [comment]
I joined the Discord awhile ago and wire was able to help me. Forgot to post here until now.

 They suggested to run `sudo rm -rf /usr/local/go` before installing and that did the trick,

**Comment by LordJuice1** [comment]
> same problem here. Is there any workarounds yet? update - just installed the 64 OS and it worked.

What did you end up doing?

**Comment by RFC1795** [comment]
> > same problem here. Is there any workarounds yet? update - just installed the 64 OS and it worked.
> 
> What did you end up doing?

I landed up installing the 64bit version. Basically went thru the ones available, till one worked lol

**Comment by RamblingGeekUK** [comment]
Install fresh and then run the scripts and all should work.
