### ISSUE TITLE
grd/ogg cannot get

### ISSUE THREAD

**Issue by unbuilt** [kercre123/wire-pod#139]
exit status 128
the package deleted?

**Comment by kercre123** [comment]
May you provide more information? It still seemed to fetch fine for me on a new device.

**Comment by unbuilt** [comment]
> May you provide more information? It still seemed to fetch fine for me on a new device.

So the setup still works for you?

I know little about Golang. Is the grd/ogg package already built and stored in the Go package center, or it need pull the source from the github reop. If it's the latter, i think the problem is the repo not exists.

**Comment by kercre123** [comment]
Yes it still works, and I just tried it in a docker container with no Go installation and it still worked. I wonder if your case was a one-time weirdness with pkg.go.dev. I see some people with similar problems get around it by setting variables related to mod cache. Maybe try removing your root Go folder (sudo rm -rf /root/go) then trying setup again?

**Comment by unbuilt** [comment]
Confirmed it's caused by network issue. It works after i use some proxy when running setup.sh and start.sh, like:
sudo GOPROXY=https://goproxy.cn ./chipper/start.sh
