### ISSUE TITLE
Web setup redirects

### ISSUE THREAD

**Issue by ThommoMC** [kercre123/wire-pod#14]
When try to upload the escapepod firmware to Vector, the website will redirect to a 404 page hosted on https://www.mildenhallmakersshed.org/noflow-devsetup/
This makes it harder for first time users to setup wire-pod.

**Comment by kercre123** [comment]
The link has been fixed. Also, I recommend [wire-prod-pod](https://github.com/kercre123/wire-prod-pod) for anyone who wants to setup a regular production bot. It will have more up-to-date instructions
