### ISSUE TITLE
Cannot use vector-wirepod-setup

### ISSUE THREAD

**Issue by weedgirl68** [kercre123/wire-pod#141]
Now this is *possibly* unrelated to this project, however I can't get past the installation process for the Vector itself. I either get the error 'GATT Server is disconnected. Cannot retrieve services. (Re)connect first with device.gatt.connect' or literally nothing happens. I've tried on several different PCs, and they all produce the same error. 

https://github.com/kercre123/wire-pod/assets/86145902/455a289f-7921-45fe-9222-6e6506786954

**Comment by kercre123** [comment]
Just to get basics out of the way: have you double-pressed his button while he is on the charger before pressing "PAIR WITH VECTOR", and is he showing a key with 6 #s on his face?
