### ISSUE TITLE
keriganc.com host not responding for vector-wirepod-setup

### ISSUE THREAD

**Issue by zbuhrer** [kercre123/wire-pod#142]
I got my Vector out and wanted to get the `wire-pod` software setup, but KC's website is timing out. This is over both local wifi and 5G, on my phone, and on my laptop ☹️ Is there a new host, maybe the README just hasn't been updated yet? 

![image](https://github.com/kercre123/wire-pod/assets/2502293/b0b1ec62-7c05-4a4e-8ab4-2b0539d60209)

**Comment by kercre123** [comment]
Should be up now.
