### ISSUE TITLE
I don't see Vector in bot settings

### ISSUE THREAD

**Issue by Saigou1** [kercre123/wire-pod#148]
Hi guys i have little problem.
After installing  wire-pod on raspberry and setting up Vector on https://keriganc.com/vector-wirepod-setup, everything went fine. But I don't see vector in wire-pod in bot settings/VECTOR CONFIGURATION. If I click on the connect button itself, the message "error: error: robot not found in SDK info file" appears. I tried 3 times to reinstall wire-pod and many times to reboot robot, followed the manuals on youtube and still the same. Do you know where could be the problem ?

**Comment by ISCoding1** [comment]
same thing
