### ISSUE TITLE
Can't activate Vector with Wire-Pod

### ISSUE THREAD

**Issue by veast-network** [kercre123/wire-pod#150]
I'm having an issue where the server will show no indication of the bot connecting with the server.
![image](https://github.com/kercre123/wire-pod/assets/86145902/3aa52a16-c8b4-4356-a414-73ac693f559f)
![image](https://github.com/kercre123/wire-pod/assets/86145902/05241adf-cd8a-4406-a740-ded1b2ffa508)
I've tried resetting the bot and retrying setup like 3 times already, nothing worked.

**Comment by kercre123** [comment]
When you set the bot up, does the Vector Setup page actually show that the authentication was successful? ("Vector is activated!" or something to that extent)

Make sure you follow the wiki for up-to-date instructions. Many tutorials are outdated and don't include the step where you need to go back to vector-wirepod-setup and complete the authentication.

**Comment by bliteknight** [comment]
> > When you set the bot up, does the Vector Setup page actually show that the authentication was successful? ("Vector is activated!" or something to that extent)
> > Make sure you follow the wiki for up-to-date instructions. Many tutorials are outdated and don't include the step where you need to go back to vector-wirepod-setup and complete the authentication.
> 
> Yeah, it'll show Vector is activated but I won't see any indication of the bot being paired to the server.

You most likely paired Vector with a 2.0/1.8 regular firmware - I have seen some users do this and it goes through like it's activated. You will need to get into factory mode and flash the wire-pod firmware and go through the activation process.

Place Vector on the charger, hold down the power button till the lights go off, sill holding down the button, then let go once you see the light come on...it should go blue at some point.

Pair and install the wire-pod firmware, it should take about 2 mins, then re-pair once its restarts and then activate. You should be taken to the set temperature, measurements screen after you click activate, then you can save the settings and you should be good to go

**Comment by gcsrtx** [comment]
Your Directions were stop on! Thanks for your help I lost connectivity and this put me back on track.
