### ISSUE TITLE
"Say Text" -Vector control (beta) does not work

### ISSUE THREAD

**Issue by MikhailVector** [kercre123/wire-pod#152]
it does nothing. (everything else in "Vector control (beta)" works excellent)

**Comment by F4310** [comment]
Hello.
This function only works when you assume Vector's control.
Click on "Assume" button, then send a text to Vector.

**Comment by MikhailVector** [comment]
> Hello. This function only works when you assume Vector's control. Click on "Assume" button, then send a text to Vector.

hi, thankfs for your input, already tried this, does not work sadly
