### ISSUE TITLE
houndify does not work

### ISSUE THREAD

**Issue by MikhailVector** [kercre123/wire-pod#153]
i created an account on houndify, enabled the only domain being "Speech to text only" and entered 

Client ID
and
Client Key

in Knowledge Graph Setup selected "houndify"

it does not work. when i ask vector "i have a question" there is the animation for question (the linked cubes) but then it fails (cubes falling down)

Jun 11 08:24:01 escapepod start.sh[594]: Checking params for candidate intent intent_knowledge_promptquestion
Jun 11 08:24:01 escapepod start.sh[594]: Bot 1 Intent Sent: intent_knowledge_promptquestion
Jun 11 08:24:01 escapepod start.sh[594]: No Parameters Sent
Jun 11 08:24:01 escapepod start.sh[594]: Bot 1 request served.

am i doing it wrong?
im used to ask him "i have a question", then he connects to the server and then i ask, then i get the answer - but this does not work

**Comment by kercre123** [comment]
Speech-to-text-only should not be the enabled domain - in this case you want an answer from Houndify, not a transcription. You need to enable disable that one and enable domains like Wikipedia, Weather, etc
