### ISSUE TITLE
Sodium related issue when attempting to start Chipper

### ISSUE THREAD

**Issue by LcorpOfficial** [kercre123/wire-pod#167]
Hello, I seem to be running into an issue when starting chipper on my RPI 3b `4.19.66-v7+`. When running `sudo ./chipper/start.sh` console responds with this error and closes.

```
# github.com/jamesruan/sodium
/root/go/pkg/mod/github.com/jamesruan/sodium@v1.0.14/aead_chacha20poly1305.go:36:2: could not determine kind of name for C.crypto_aead_chacha20poly1305_ietf_keygen
```

I have followed steps up to this point and selected picovoice as the provider (was told by console to do so due to platform)

**Comment by kercre123** [comment]
Closing because I have removed sodium from wire-pod
