### ISSUE TITLE
Is the Keriganc server down? 

### ISSUE THREAD

**Issue by Olivo96** [kercre123/wire-pod#179]
is the Keriganc site down?

Hello!  
I'm trying to install the Wire-pod to my vector, but I can't access the  [https://keriganc.com/vector-wirepod-setup] website 

also on the powershell command it gives me this error when following the guide
 

10. In Powershell, run the following commands:
    cd ~ curl -o wsl-firewall.ps1 https://keriganc.com/wsl-firewall.ps1 .\wsl-firewall.ps1

I get this error

    curl : Unable to connect to the remote server
    At line:2 char:1
    + curl -o wsl-firewall.ps1 https://keriganc.com/wsl-firewall.ps1
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
       eption
        + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    
    .\wsl-firewall.ps1 : The term '.\wsl-firewall.ps1' is not recognized as the name of a cmdlet, function, script file,
    or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
    try again.
    At line:3 char:1
    + .\wsl-firewall.ps1
    + ~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (.\wsl-firewall.ps1:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException
    

Does anybody know what i'm doing wrong? :(

Thank you!

**Comment by kercre123** [comment]
It was down. It should be up now
