### ISSUE TITLE
Vector not reponse "Hey Vector"

### ISSUE THREAD

**Issue by nguyenhunga5** [kercre123/wire-pod#191]
My vector cannot response "Hey Vector" command and after pressing the back button, I say something but do not get any response.
I checked on log, I saw some information
<img width="372" alt="image" src="https://github.com/kercre123/wire-pod/assets/853275/ced74d57-e1ea-48b0-862f-1e7c36e8f87c">

<img width="491" alt="image" src="https://github.com/kercre123/wire-pod/assets/853275/dd8aa07f-777d-4239-a59f-de1441b7c4b1">

Thank you for doing great.

**Comment by bliteknight** [comment]
You may have bad microphones. Watch this video to get to the hidden menu and see what the values are for the mics
https://www.youtube.com/watch?v=hOt4iw17yn0

**Comment by nguyenhunga5** [comment]
> You may have bad microphones. Watch this video to get to the hidden menu and see what the values are for the mics https://www.youtube.com/watch?v=hOt4iw17yn0

Thank you for your response, I cannot go to hide the menu, I don't know the reason. But yesterday, I went go hide the menu and saw the microphone work.

**Comment by nguyenhunga5** [comment]
> You may have bad microphones. Watch this video to get to the hidden menu and see what the values are for the mics https://www.youtube.com/watch?v=hOt4iw17yn0

after teardown my vector and cleaning the cable, it working now. Thank you so much.
