### ISSUE TITLE
Use SDK or REST access to Vector

### ISSUE THREAD

**Issue by MTrab** [kercre123/wire-pod#20]
Anyone managed to get SDK to work WITHOUT setting up Vector with the companion app first?
I have one Vector that have never been on DDL servers and never will be.

But I cannot access the SDK for him.

**Comment by kercre123** [comment]
If you have a dev/OSKR bot then it is theoretically possible, but a production robot requires setup via the companion app for the gateway API to function.

**Comment by kercre123** [comment]
Closing as the request is not in the scope of wire-pod (yet?).
