### ISSUE TITLE
wire-pod is good. but, There's no response to the comment "hey vector"

### ISSUE THREAD

**Issue by dracula0707** [kercre123/wire-pod#204]
The wire-pod is well installed and the vector is also well set, but there is no reaction to the "hey vector" comment. 
Of course, commands sent from the vector web perform well. What's the problem?

**Comment by NonaSuomy** [comment]
Did it work before? Maybe try using some text-to-speech website to see if it's an accent issue.

**Comment by Thehlyone** [comment]
i had the exact same issue, I checked and then opened port 884 and then (vector web ui changed locale english gb -> english au) as this made him understand my scottish accent lol

**Comment by dracula0707** [comment]
Thank you. It's been resolved. It's good to switch to english(au). ^^
