### ISSUE TITLE
Issue with Bot Settings

### ISSUE THREAD

**Issue by apeoplerson** [kercre123/wire-pod#214]
Not sure why this is happening. Hopefully it something easy. Sorry should of been more specific. This happen in the web interface when you go to try to connect.

error: rpc error: code = Unimplemented desc = unknown service Anki.Vector.external_interface.ExternalInterface

**Comment by elliot-holley** [comment]
Having the same issue, running on a vector 1.0 on WSL. everything else works fine.

**Comment by bumbleb0321** [comment]
I believe I am also having the same issue through wsl on a Windows 11 device. When trying to open bot settings (to set up voice among other things) I receive the error pop up :

escapepod.local:8080 says
error: rpc error: code = Unimplemented desc = unknown service
Aniki.Vector.external_interface.ExternalInterface

**Comment by bliteknight** [comment]
You cannot connect to your bots when you install via WSL

Wire just released a native version that runs on windows so you can give that a try

**Comment by lukeb12798** [comment]
I just used the windows version but it said the same thing.
