### ISSUE TITLE
cannot get vector to flash firmware

### ISSUE THREAD

**Issue by DIRECTVIRUS** [kercre123/wire-pod#218]
![image](https://github.com/kercre123/wire-pod/assets/114742636/8cbdd7c7-1b56-4390-a906-092dce48d20b)

whenever I try to ota-start using either a locally hosted web server for the file or the link in the guide the vector robot never begins the download and therefore cannot connect to wirepod as it cannot flash to the custom firmware

![image](https://github.com/kercre123/wire-pod/assets/114742636/fae0c09b-f67d-4b49-a31e-baa5cec10d85)

**Comment by kercre123** [comment]
You have to go to recovery mode first by placing Vector on the charger and holding the button for 15 seconds. The firmware must report as v0.9.0.

**Comment by DIRECTVIRUS** [comment]
that was it thank you. thought I had him in recovery mode.
