### ISSUE TITLE
Wire-pod server crash 9 novembre 2023

### ISSUE THREAD

**Issue by krunch-krunchy** [kercre123/wire-pod#225]
Hi, i've recently installed wire-pod on win10, but when i'm trying to start the wire-pod server it crashes;
It gives me thoses errors and i don't how i could solve them:

 [zeroconf] no suitable IPv4 interface: udp4: failed to join any of these interfaces: [{7 1500 eth2 8b:c6:3b:1d:6a:59 up|broadcast|multicast} {61 1500 eth3 0b:00:27:00:00:3d up|broadcast|multicast}]
wire-pod started successfully!
 [zeroconf] no suitable IPv6 interface: udp6: failed to join any of these interfaces: [{7 1500 eth2 8b:c6:3b:1d:6a:59 up|broadcast|multicast} { up|broadcast|multicast}] 
exit status 2

Thanks in advance

**Comment by kercre123** [comment]
The latest commit should fix this. Run:

```
cd ~/wire-pod
git pull
```

Then try starting it again.

**Comment by krunch-krunchy** [comment]
Thanks, it solved this problem, now i'm habing trouble pairing the vector setup page with vector but it's another issue, thanks for your help
