### ISSUE TITLE
open ai api

### ISSUE THREAD

**Issue by nickdg101** [kercre123/wire-pod#229]
Hi there, i have managed to get all setup with wire pod, thanks team, great product.
I am having issue with the open ai api, i logged into open ai and got an api key and added it, but when i ask my vector a question he responds with “open ai is not responding”
Any ideas anyone?
Thanks

**Comment by edd134** [comment]
I'm pretty sure that you have to pay for open ai api :(

**Comment by IxZOMBxI** [comment]
U have to pay but it not much. Just go set your monthly allowance amount on open ai.
