### ISSUE TITLE
Custom Intents destroy all other phrases 

### ISSUE THREAD

**Issue by stromtroopertk421** [kercre123/wire-pod#231]
While trying custom intents, he will default all activating phrases to the first custom intent set. While trying to get him to understand new phrases for find cube, and then telling him to go explore, he still finds his cube with all phrases. Even if setting up a new intent with the action he lost, the log reports the correct intent, he still will only find his cube. 

He is in the latest 2.0.1.6076 firmware. Everything works normal so long as i dont set up any custom intents. 

Edit1: Wirepod latest windows release running on windows 10 latest update.

**Comment by kercre123** [comment]
May you upload your customIntents.json file?

(can be found by right clicking the wire-pod icon in the system tray at the bottom right and clicking "Config folder")
