### ISSUE TITLE
change vector’s wifi

### ISSUE THREAD

**Issue by Pane82** [kercre123/wire-pod#233]
there is a way to change vector’s connected wifi without wiping his data?

**Comment by edd134** [comment]
I'm pretty sure if you start wire pod this new wifi network, you can choose this new one on vector setup (not sure tho)

**Comment by Pane82** [comment]
i’ve tried but he cannot connect to the pod…

**Comment by edd134** [comment]
turn off the old wifi

**Comment by Pane82** [comment]
well he auto select it anyways

**Comment by edd134** [comment]
are you  going onto the vector setup page?

**Comment by Pane82** [comment]
yep i’ve tried but it set the old wifi and i cannot change it

**Comment by kercre123** [comment]
Theoretically, you should be able to head to [noflow-devsetup](https://www.project-victor.org/noflow-devsetup) and use BLE commands to get him to forget a network and join a new one. Connect like normal, but do NOT check "Enable auto-setup flow" when connecting. Use `help` to figure out what commands do what. For `anki-auth`, you should be able to use any random string (ex. `anki-auth asdjoasdoiqwoijd`).

**Comment by bliteknight** [comment]
> Theoretically, you should be able to head to [noflow-devsetup](https://www.project-victor.org/noflow-devsetup) and use BLE commands to get him to forget a network and join a new one. Connect like normal, but do NOT check "Enable auto-setup flow" when connecting. Use `help` to figure out what commands do what. For `anki-auth`, you should be able to use any random string (ex. `anki-auth asdjoasdoiqwoijd`).

This is the only way I have verified to change his Wifi. Once you get in the "noflow" terminal, there is a command to wipe all wifi connections - but you have to anki-auth before you do so. Once you run that command you will be able to clear all connections and join the new one using 
wifi-scan
wifi-join "Wifi Access point" "Wifi password"

**Comment by Hitojoy** [comment]
> Theoretically, you should be able to head to [noflow-devsetup](https://www.project-victor.org/noflow-devsetup) and use BLE commands to get him to forget a network and join a new one. Connect like normal, but do NOT check "Enable auto-setup flow" when connecting. Use `help` to figure out what commands do what. For `anki-auth`, you should be able to use any random string (ex. `anki-auth asdjoasdoiqwoijd`).

anki-auth won't work,failed to authorize

**Comment by Zomboy4313** [comment]
What I do is put vector on his charger, double press his back button and connect. Then I just go though the setup process, and connect to new WiFi. Did this to my phone hotspot earlier today.
