### ISSUE TITLE
It won't connect

### ISSUE THREAD

**Issue by Carlos2278** [kercre123/wire-pod#254]
Vector won't connect to https://vector.techshop82.com/html/main.html

What are you running wire-pod on?
[OS]: Windows
[Hardware]: Intel(R) Core(TM) i7-3770 CPU GTX 1650 GPU Windows 10 Home 22H2

It's a Prod bot

I have tried by following this https://github.com/kercre123/wire-pod/wiki/Installation
I can't access escapepod.local 
![image](https://github.com/kercre123/wire-pod/assets/79020314/6ef9f92e-e96c-42aa-953a-2078183ce887)
I was able to access https://vector.techshop82.com/html/main.html but wasn't able to pair Vector to it, when I press the "PAIR WITH VECTOR" button it shows my Vector but when I press it, it just takes me back to the "PAIR WITH VECTOR" screen. My vector's OS is 0.9.0 (V4).

Video of what is happening👇
https://github.com/kercre123/wire-pod/assets/79020314/7c72057d-afc1-4d50-9be9-32a3df06aa87

Picture of Vector's information👇
![20231216_191212](https://github.com/kercre123/wire-pod/assets/79020314/6efcb70e-44d6-442b-9b1a-cb72117d63a1)

**Comment by Nitheshwar27** [comment]
Follow this link: https://www.youtube.com/watch?v=8Hun_F3WGF8 this is how I setup my wirepod for free

**Comment by Carlos2278** [comment]
Thanks
