### ISSUE TITLE
Temperature units not respected

### ISSUE THREAD

**Issue by labomat** [kercre123/wire-pod#261]
**Describe the bug**
I changed the temperature unit setting on the vector configuration page to celsius but the weather report stil uses fahrenheit values for temperature.

**To Reproduce**
1. Go to '[...](http://escapepod.local:8080/sdkapp/settings.html?serial=xxxxxxx)'
2. Click on 'Temperature units'
3. Change to 'Celsius'
4. Ask vector about the weather
5. Answer shown on screen is fahrenheit

**Expected behavior**
If settings changed, all temperature should be dsplayed in celsius

**Device you are running wire-pod on (please complete the following information):**
 - OS: WirePod on MacOS 12.7.2 (Monterey)
 - Hardware: MacBook Pro (2015)

**Comment by kercre123** [comment]
Fixed in the latest release. Sometimes Vector wouldn't sent a WriteJdocs request to wire-pod when settings were changed. wire-pod now fetches the latest Vector Jdocs whenever a setting is changed, so it is always synced.
