### ISSUE TITLE
[BUG] Spelling Recieved -> Received 

### ISSUE THREAD

**Issue by NonaSuomy** [kercre123/wire-pod#274]
**Describe the bug**

Recieved -> Received 

```
I usually come before E,
except after C,
Or when sounded as "a",
As in neighbor and weigh
But seizure and seize do what they please.
```

I checked most of the code base I think and found it in these 5 spots...

https://github.com/kercre123/wire-pod/blob/056b63397b8ac6efbf62a308075a803cf247abe0/chipper/pkg/servers/chipper/connectioncheck.go#L41

https://github.com/kercre123/wire-pod/blob/056b63397b8ac6efbf62a308075a803cf247abe0/chipper/pkg/servers/chipper/connectioncheck.go#L49

https://github.com/kercre123/wire-pod/blob/056b63397b8ac6efbf62a308075a803cf247abe0/chipper/pkg/wirepod/preqs/stream_houndify.go#L48

https://github.com/kercre123/wire-pod/blob/056b63397b8ac6efbf62a308075a803cf247abe0/chipper/pkg/wirepod/sdkapp/jdocspinger.go#L106

https://github.com/kercre123/wire-pod/blob/056b63397b8ac6efbf62a308075a803cf247abe0/chipper/pkg/wirepod/stt/houndify/Houndify.go#L78

Noticed it in this log I got:
```
Haven't recieved a conn check from 00###### in 15 seconds, will ping jdocs on next check
Broadcasting mDNS now (outside of timer loop)
Jdocs: Incoming ReadDocs request, Robot ID: vic:00######, Item(s) to return: 
[doc_name:"vic.AppTokens"]
Successfully got jdocs from 00######
```

**Comment by kercre123** [comment]
Fixed

**Comment by NonaSuomy** [comment]
Thank you
