### ISSUE TITLE
[BUG] “Hey Vector, Listen to music” Does not work, you need to say “Hey Vector, Listen to the Beat”

### ISSUE THREAD

**Issue by TypicalZedF** [kercre123/wire-pod#281]
**Describe the bug**
“Hey Vector, Listen to music” Does not work, you need to say “Hey Vector, Listen to the Beat” which is a little weird considering they are the same commands just about.
```
2024.01.29 19:46:23: Intent matched: intent_system_noaudio, transcribed text: 'listen to music', device: 006089e6
2024.01.29 19:46:35: Intent matched: intent_imperative_dance, transcribed text: 'listen to the beat', device: 006089e6
```

**To Reproduce**
Ask Vector to Listen to the beat, then ask him to listen to the music after. The commands do not act the same or get registered the same.

**Expected behavior**
Vector should respond correctly to both phrases

**Device you are running wire-pod on (please complete the following information):**
 - OS: Windows 11 Pro
 - Hardware: Nividia 1650 Super, Ryzen 5 3500 6 - Core, 16GB RAM DDR4

**Comment by kercre123** [comment]
fixed
