### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jamesfawcett** [kercre123/wire-pod#296]
**Describe the bug**
GPT Prompt not saving on latest update. After refresh or revisiting the page, it says "undefined".

**To Reproduce**
Go to :8080/setup.html
Enter a prompt, or the default. 
Save

**Expected behavior**

**Screenshots**
![image](https://github.com/kercre123/wire-pod/assets/5245272/48311f7d-f883-4a9e-9201-7eacb3b5d6c9)

**Device you are running wire-pod on (please complete the following information):**
 - Hardware: Armbian
 
Console logs:

![image](https://github.com/kercre123/wire-pod/assets/5245272/12402448-4602-4bcc-8209-25cbb810fbde)

updateIntentSelection("editSelect")
updateIntentSelection("deleteSelect")
createIntentSelect("intentAddSelect") <---

**Comment by kercre123** [comment]
How exactly did you update it? It seems like the webroot has been updated, but the actual server code hasn't been recompiled. You probably need to rebuild the binary, which can be accomplished with the steps here [https://github.com/kercre123/wire-pod/wiki/Things-to-Know#linux](https://github.com/kercre123/wire-pod/wiki/Things-to-Know#linux)

**Comment by jamesfawcett** [comment]
Thank you @kercre123 I'd not seen these other pages of the Wiki - just checking :)

**Comment by jamesfawcett** [comment]
@kercre123 thank you - I was only half upgraded! I see the changed custom intents screen now, thank you for all your hard work :)
