### ISSUE TITLE
How to replace TTS

### ISSUE THREAD

**Issue by unbuilt** [kercre123/wire-pod#3]
Thanks for the great project. I followed the changes, and replaced STT using Azure STT. And I want to replace the TTS, have you tried this ?

**Comment by kercre123** [comment]
You mean you want to replace the text-to-speech on Vector?

**Comment by unbuilt** [comment]
Yes, i want to replace text to speech with Azure TTS.
Then change Q&A service too, i think the Q&A service should be in cloud, so it may be easier.

**Comment by kercre123** [comment]
That would require DDL to release more source code and it would be out of the scope for this project, since it is done locally on Vector and not in a server. For replacing the Q&A service, I would look in the knowledgegraph.go file
