### ISSUE TITLE
[HELP] Could you please set the Japanese language so that I can use it in Japan?

### ISSUE THREAD

**Issue by pizzicatox** [kercre123/wire-pod#305]
There is a Japanese item in the settings, but Japanese cannot be used.
I would be happy if I could at least use Japanese with openAI...

**Comment by kercre123** [comment]
The Japanese locale not working is a limitation of Vector's firmware. It was taken out in 1.7 for whatever reason - and 1.6< doesn't work with wire-pod.

As for adding the language to wire-pod, someone who speaks Japanese will have to come around and add it themselves. I only speak English. The other languages were added thanks to pull requests.
