### ISSUE TITLE
[BUG] Virus in Windows Installer .exe

### ISSUE THREAD

**Issue by wmevius** [kercre123/wire-pod#307]
**Describe the bug**
Windows Defender detects a virus when downloading the Installer .exe (v1.1.10). Trojan:Win32/Wacatac.B!ml

**To Reproduce**
Download WirepodInstaller-v1.1.10.exe (better not...) on a machine with up-to-date Windows 10 or 11

result:
File removed by Windows Defender

**Expected behavior**
no virus in installer...

**Device you are running wire-pod on (please complete the following information):**
 Windows 10 or 11

**Additional context**
could maybe come from the machine the .exe was created on

**Comment by kercre123** [comment]
It's a false positive.
