### ISSUE TITLE
Vector reports the wrong date

### ISSUE THREAD

**Issue by MimoAW** [kercre123/wire-pod#332]
When I ask Vector what's the date? He always says it's sometime in 2023 even though it's 2024 and I can't see where to change the date in wirepod interface. Can someone please help me?

Milo

**Comment by kercre123** [comment]
"What is the date" is not an embedded command, so that is automatically offloaded to whatever service you set for knowledge graph. OpenAI and Together are LLMs and won't give accurate information.

**Comment by MimoAW** [comment]
Ok thanks for your help!

Milo
