### ISSUE TITLE
Error logging in. The bot is likely unable to communicate with your wire-pod instance. Make sure you followed all of the steps and try again.

### ISSUE THREAD

**Issue by skunkfpv** [kercre123/wire-pod#338]
Hello. I have tried everything and the wirepod is running on the same ip (10.0.) but it is unable to connect (Error logging in. The bot is likely unable to communicate with your wire-pod instance. Make sure you followed all of the steps and try again.) The server is running on popos and ive already updated his firmware like 5 times. PLZ HELP THANKS

**Comment by Zomboy4313** [comment]
A lot of people come here with these issues, do you know if your router allows mDNS. This issue is out of WirePods control

**Comment by kercre123** [comment]
https://github.com/kercre123/wire-pod/issues/336
