### ISSUE TITLE
Replace the vosk model ...

### ISSUE THREAD

**Issue by EchoInCloud** [kercre123/wire-pod#34]
Tested... it's worth replacing the vosk-model-small-en-us-0.15 in the wire --> https://alphacephei.com/vosk/models vosk-model-en-us-0.22-lgraph

**Comment by EchoInCloud** [comment]
For already installed Wire:

Download model and extract  in "/home/pi/Downloads" ...

..from pi user.. 
sudo cp -r ./Downloads/vosk-model-en-us-0.22-lgraph/am /home/pi/wire-pod or wire-prod-pod/vosk/models/en-US/model/
sudo cp -r ./Downloads/vosk-model-en-us-0.22-lgraph/conf /home/pi/wire-pod or wire-prod-pod/vosk/models/en-US/model/
sudo cp -r ./Downloads/vosk-model-en-us-0.22-lgraph/graph /home/pi/wire-pod or wire-prod-pod/vosk/models/en-US/model/
sudo cp -r ./Downloads/vosk-model-en-us-0.22-lgraph/ivector /home/pi/wire-pod or wire-prod-pod/vosk/models/en-US/model/

sudo reboot

**Comment by kercre123** [comment]
Tried it out, the performance on some of my hardware is not great with it so I will not make the 0.22 model default. I may add it as an option though.
