### ISSUE TITLE
[Feature Request] Support for ollama (local LLMs)

### ISSUE THREAD

**Issue by JMcrafter26** [kercre123/wire-pod#340]
Hey,
I saw there is support for OpenAI, so the structure for the request and response is there. This means it would be easy to implement an option for [Ollama](https://github.com/ollama/ollama) (Local LLMs, same api as OpenAI).

Please consider adding this, this would be very useful!

**Comment by TypicalZedF** [comment]
I agree! I have Ollama installed on my Linux Server. I would enjoy a way to take Ollama output and run it through wire-pod. It's free and runs on your hardware!

**Comment by ocueye2** [comment]
I dont know exactly how this works so take with a grain of salt but it should be as easy as adding a defined ip addr wherever the gpt api is defined

**Comment by JMcrafter26** [comment]
Ollama uses the same api structure as OpenAI so it should be easy. You just need to be able to edit the endpoint and the model you want to use

**Comment by LordJuice1** [comment]
This seems pretty similar to this request. Which I'm currently trying myself. I'm not sure where/how to make it where you can change it on the escapepod page and not in the script

https://github.com/kercre123/WirePod/issues/16#issue-2354622490

**Comment by kercre123** [comment]
A "Custom" option for Knowledge Graph has been added, which lets you enter a custom endpoint.

**Comment by JMcrafter26** [comment]
Thank you!

**Comment by LordJuice1** [comment]
Thanks Wire!

**Comment by thefunkygibbon** [comment]
does it work?  I've put in my ollama server details
api key = ollama
endpoint = http://192.168.0.2:11434/api
model = (tried a bunch but for arguments sake using) llama3:latest (or is it just llama3  ?  I've tried both and both don't seem to work. 

every time i try to use vector it just tells me cannot connect to the LLM
`
2024.09.20 17:52:15: LLM error: error, status code: 404, message: json: cannot unmarshal number into Go value of type openai.ErrorResponse
2024.09.20 17:52:15: Intent matched: intent_system_unmatched, transcribed text: 'what's the answer to life the universe and everything', device: 00601532
`

**Comment by JMcrafter26** [comment]
It worked in the past, but I tested it today (with a different setup) and I also can't get it to work

**Comment by LordJuice1** [comment]
I'll admit, I'm not running the latest version. But, this is how my config page looks like. I'm also using OpenWebUI for my Ollama/llm needs.
`API Key- sk-167c2*****4cd4a************(this is a 35 character API key)`
`API Endpoint- http://xxx.xxx.xxx.xxx:11434/v1`
`Model name- llama3`

**Comment by JMcrafter26** [comment]
I tried again and it worked.
My settings:
KEY: ollama
URL: http://192.168.2.146:11434/v1
MODEL: llama3.1:latest

**Comment by uyuutityiugyu** [comment]
How did you find your url and will it be the same for mine
