### ISSUE TITLE
Request: Way to stop LLM response

### ISSUE THREAD

**Issue by MicaelJarniac** [kercre123/wire-pod#362]
Sometimes, I'm trying to tell Vector to do something, and the STT gets it wrong. It then doesn't get matched to a predefined sentence and is sent to the LLM. The response from the LLM is sometimes quite long, resulting in having to wait quite a while for Vector to stop talking.

It'd be nice to have something, like a press of its button or a pet on the back, to stop it from talking.

**Comment by Zomboy4313** [comment]
A workaround I have is to tell the LLM "If a question seems cut off or you do not understand it, answer with “.{{playAnimationWI||confused}}.” And nothing else. This should make the LLM only play the animation. I tried with just a full stop but WirePod would crash for me

**Comment by MicaelJarniac** [comment]
Closed by #368.
