### ISSUE TITLE
Error logging in. The bot is likely unable to communicate with your wire-pod instance.

### ISSUE THREAD

**Issue by aceheart676** [kercre123/wire-pod#365]
**Describe the issue:**

I've installed it and ran it on 3 different things for the past 13 hours (android, Windows, and Debian on pi4) trying to set up a regular vector and I've uninstalled and installed it several times and it keeps saying "Error logging in. The bot is likely unable to communicate with your wire-pod instance."

**Comment by Zomboy4313** [comment]
Other people have already posted this issue, is had WirePod worked before. Check if your router support mDNS

**Comment by kercre123** [comment]
https://github.com/kercre123/wire-pod/issues/336#issue-2320196665
