### ISSUE TITLE
[BUG] SDK doesn't seem to work on newer versions

### ISSUE THREAD

**Issue by Zomboy4313** [kercre123/wire-pod#379]
**Describe the bug**

I'm not sure what happened but when i tried to use the sdk i was getting errors, reinstalling the sdk keeps failing to download the certificates by the looks of it. I'm using the SDK on a Mac and WirePod is installed on a Windows Machine

**To Reproduce**

Install SDK

**Expected behavior**

It should not fail 

**Screenshots**
![image](https://github.com/user-attachments/assets/a3f14aad-6dd6-4c8e-aaaa-a07c087855c8)

**Device you are running wire-pod on (please complete the following information):**
 - OS: Windows
 - Hardware: AMD Ryzen 7 5700U Mini PC

**Comment by kercre123** [comment]
This means you didn't clear user data before setting up wire-pod or there was some problem during authentication. This is the "weird behavior" that was described.

**Comment by Zomboy4313** [comment]
Ah ok, that makes sense as I just reinstalled Windows and thus WirePod and didn't realise this is the weird behaviour that happens

**Comment by Zomboy4313** [comment]
Can confirm this fixed my issue, thanks and sorry for not trying this out beforehand
