### ISSUE TITLE
pkg-config --cflags  -- alsa --> pkg-config: exit status 1 "error"...

### ISSUE THREAD

**Issue by EchoInCloud** [kercre123/wire-pod#40]
:Đ

sudo ./chipper/start.sh
output:
"
pkg-config --cflags  -- alsa
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
pkg-config: exit status 1
"

...a good idea to mention the necessary dependencies...

Fixing: 
sudo apt-get install libasound2-dev

..welcome..

-------------------------
./chipper/start.sh
"
Loading plugins
Not loading placeholder. Plugins must be built with 'go build -buildmode=plugin' and must end in '.so'.
Not loading sdkTest.go. Plugins must be built with 'go build -buildmode=plugin' and must end in '.so'.
Houndify for knowledge graph initialized!
"
.. what should I do with this?

**Comment by kercre123** [comment]
Should be fixed now

That is normal output
