### ISSUE TITLE
Chipper Issue

### ISSUE THREAD

**Issue by mdinolfo123** [kercre123/wire-pod#44]
When I try to start Chipper, I get:

pkg/sdkapp/server.go:19:2: missing go.sum entry for module providing package github.com/fforchino/vector-go-sdk/pkg/vector (imported by github.com/digital-dream-labs/chipper/pkg/sdkapp); to add:
	go get github.com/digital-dream-labs/chipper/pkg/sdkapp
pkg/sdkapp/server.go:20:2: missing go.sum entry for module providing package github.com/fforchino/vector-go-sdk/pkg/vectorpb (imported by github.com/digital-dream-labs/chipper/pkg/sdkapp); to add:
	go get github.com/digital-dream-labs/chipper/pkg/sdkapp

**Comment by kercre123** [comment]
Fixed now, cd into the wire-pod directory and run `sudo ./update.sh`

**Comment by mdinolfo123** [comment]
Thank you so much!
