### ISSUE TITLE
SSH on WireOS

### ISSUE THREAD

**Issue by ibwo88** [kercre123/wire-pod#48]
Hi, would like confirm if there is SSH on WireOS like OSKR? I am unable to SSH to vector after flashing. All things seems working but I am not able to SSH.
Did a nmap and only found port 443 listening on the vector. Help

**Comment by ibwo88** [comment]
My bot is a PROD bot. Does activating the Wire-Pod enable the SSH?

**Comment by Skybird129** [comment]
WireOS is a custom firmware for Vector. You can it only install on unlocked (OSKR) or development bots. As far as I know there is no SSH for locked (PROD) bots.

**Comment by kercre123** [comment]
Skybird is correct, the OTA vector-epod-setup flashes on the bot is the escape pod OTA, and it does not have any special dev features enabled. You have to get OSKR or a dev-unlocked bot to be able to use SSH.
