### ISSUE TITLE
I got pinged in a random discussion post... don't know why, but kinda want it removed ngl

### ISSUE THREAD

**Issue by sparty182020** [kercre123/wire-pod#55]
the comment contains "nsfw" (not gonna click the link as its prob a scam), but there were others also pinged so I was hopping it could get removed and/or reported...

Link: https://github.com/kercre123/wire-pod/discussions/24#discussioncomment-4519164

**Comment by sparty182020** [comment]
also looking at the top languages in this repo, I have no experience in the top 2, but have some Shell experience and I know a lot of HTML, CSS, and Javascript so if you need any help with that, lmk

**Comment by kercre123** [comment]
A couple of those comments were made, they have been reported and the associated posts have been deleted. Sorry about the ping.

**Comment by sparty182020** [comment]
Its all cool man. Like i said, I can also help with any HTML, JavaScript, or CSS code if it isn't working as I'm good at those languages
