### ISSUE TITLE
Timer Duration Interpreted Incorrectly

### ISSUE THREAD

**Issue by bernalfr** [kercre123/wire-pod#58]
Instructing the Vector to start a timer that is longer than a minute (e.g., by saying: “Hey Vector... Set a timer for five minutes.”) results in a timer set for one minute.

Log output:
_Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
(Bot 1) End of speech detected.
**Bot 1 Transcribed text: set a timer for five minutes**
Not a custom intent
Partial match for intent intent_clock_settimer_extend (timer)
Found bot config for 00000000
Checking params for candidate intent intent_clock_settimer_extend
Seconds parsed from speech: 60
Bot 1 Intent Sent: intent_clock_settimer_extend
Bot 1 Parameters Sent: map[timer_duration:60]
Bot 1 request served._ 

Setting a timer in seconds (e.g., by saying: “Hey Vector... Set a timer for ninety seconds.”) works more sporadically depending on the duration.

Log output:
_Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
(Bot 1) End of speech detected.
**Bot 1 Transcribed text: set a timer for forty five seconds**
Not a custom intent
Partial match for intent intent_clock_settimer_extend (timer)
Found bot config for 00000000
Checking params for candidate intent intent_clock_settimer_extend
Seconds parsed from speech: 45
Bot 1 Intent Sent: intent_clock_settimer_extend
Bot 1 Parameters Sent: map[timer_duration:45]
Bot 1 request served.
Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
(Bot 1) End of speech detected.
**Bot 1 Transcribed text: that a timer for ninety seconds**
Not a custom intent
Partial match for intent intent_clock_settimer_extend (timer)
Found bot config for 00000000
Checking params for candidate intent intent_clock_settimer_extend
Seconds parsed from speech: 99
Bot 1 Intent Sent: intent_clock_settimer_extend
Bot 1 Parameters Sent: map[timer_duration:99]
Bot 1 request served.
Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
(Bot 1) End of speech detected.
**Bot 1 Transcribed text: set a timer for one hundred eighty seconds**
Not a custom intent
Partial match for intent intent_clock_settimer_extend (timer)
Found bot config for 00000000
Checking params for candidate intent intent_clock_settimer_extend
Seconds parsed from speech: 81
Bot 1 Intent Sent: intent_clock_settimer_extend
Bot 1 Parameters Sent: map[timer_duration:81]
Bot 1 request served._

**Comment by kercre123** [comment]
Just pushed some changes to the word2num function, those phrases should work now as long as you update. I had to create my own words-to-number parser since I couldn't find one already available for Go.
