### ISSUE TITLE
Bug in timer function

### ISSUE THREAD

**Issue by Hamlet3000** [kercre123/wire-pod#73]
### Discussed in https://github.com/kercre123/wire-pod/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **Hamlet3000** January 27, 2023</sup>
When using the timer function via the interface, Vector always counts backwards from 48, no matter what value you enter in the field.
![Screenshot_20230127_101623](https://user-images.githubusercontent.com/75612866/215051458-cfe7b84a-58be-43bf-9ded-c94a35f9ab18.jpg)
</div>

**Comment by kercre123** [comment]
This seems to be a fault of the Vector software itself, or I am missing something obvious. Timer is done via app intents, which accepts an intent string and a param string. No matter what I put into param, the timer always ends up being a multiple of 16. I decided to just replace it with a stimulation meter, as timer is pretty stable with voice command by this point
