### ISSUE TITLE
most of the settings don't work anymore

### ISSUE THREAD

**Issue by Hamlet3000** [kercre123/wire-pod#76]
The last built seems broken. Most of the settings don't work anymore like Volume, Locale, Temperature Units, Button Action, Set Location, and Set Time Zone.

I have completely reinstalled your original branch.

**Comment by kercre123** [comment]
Try going to :8080/sdkapp and running Ctrl+Shift+R (CMD+Shift+R on Mac) on the main webpage to redownload all of the scripts and such, they may be caching

**Comment by Hamlet3000** [comment]
I have already done that. I have completely re-downloaded the sources and gone through the full istallation process. I have also tried different browsers on different machines.

**Comment by kercre123** [comment]
Do any errors appear in the wire-pod logs or the browser log?

**Comment by Hamlet3000** [comment]
no, the green dot just jumps back to the previous setting, if I try to change something.

**Comment by Hamlet3000** [comment]
And I'm not sure if it's related, but Vector crashes with error code 915 when I try set location

**Comment by kercre123** [comment]
What device is wire-pod running on? May you pull logs from the robot and get them to me? (can be done by heading to [https://www.project-victor.org/noflow-devsetup](https://www.project-victor.org/noflow-devsetup), connecting the robot, and entering `logs` in the console)

**Comment by Hamlet3000** [comment]
Its running on an RaspberryPi 4B with 4GB Ram.
Vectors log is attached

[vector-logs-2023-02-04-08-54-06.tar.zip](https://github.com/kercre123/wire-pod/files/10608205/vector-logs-2023-02-04-08-54-06.tar.zip)

**Comment by ThommoMC** [comment]
I also Raspberry Pi 4B with 4G ram, I can confirm it works perfectly without any issues. I am able to change any of Vector’s settings without any issues.

**Comment by Hamlet3000** [comment]
I tired to get back to DDL servers and restored the original server_config.json on Vector. When trying to set up Vecot via the Android app, the error 923 came up. neither a reboot nor the complete new setup via wire-pod works now. After a few seconds in which Vector shows his eyes, appears again the error 923.

**Comment by Hamlet3000** [comment]
It seems that the problem was indeed with my Vector. I flattened everything again and installed the latest OSKR firmware 1.8.1. Now everything works again as it should. Please excuse the confusion

**Comment by iPsych** [comment]
> It seems that the problem was indeed with my Vector. I flattened everything again and installed the latest OSKR firmware 1.8.1. Now everything works again as it should. Please excuse the confusion

Hello,
I am experiencing same 923 error. How did you loaded latest OSKR firmware 1.8.1?

**Comment by Hamlet3000** [comment]
I used the EscapePod from DDL to reinstall the latest OSKR firmware. There is the possibility to upload .ota files and reinstall Vector with them.
But maybe it's really just a buggy version of vic-cloud or vic-gateway.... (?)

**Comment by iPsych** [comment]
> I used the EscapePod from DDL to reinstall the latest OSKR firmware. There is the possibility to upload .ota files and reinstall Vector with them. But maybe it's really just a buggy version of vic-cloud or vic-gateway.... (?)

I think so... Maybe I have to do it with latest EscapePod?
Do you have .OTA of 1.8.1? If so, can you share file/link, please?

**Comment by Hamlet3000** [comment]
I think that the OSKR firmware is hard linked to the serial number of the Vector, so it is not possible to share it. My .ota would probably not work for you.

**Comment by Hamlet3000** [comment]
Have you tried contacting DDL to have them resend you the latest 1.8.1 OSKR image für your robot? Steve Coblentz is always very cooperative on Facebook.

**Comment by iPsych** [comment]
@Hamlet3000 Thanks. I sent a message to him. Did you ask help through facebook directly?

**Comment by Hamlet3000** [comment]
@iPsych yes, I contacted Steve directly through Facebook. He usually replies within a day
