### ISSUE TITLE
Houndify keeps saying "I didn't get that"

### ISSUE THREAD

**Issue by Manic137** [kercre123/wire-pod#94]
I'm not sure if this is an issue at all or is just a limitation of the technology, but there's some questions Houndify just immediately gets, and some of them that are less westernized, like for example, I asked "When did Malaysia change it's name to Malaysia", no matter how many times, it's always "I didn't get that", I've also asked who a twitch streamer was, same response sadly.

**Comment by kercre123** [comment]
That is a Houndify issue. You may be able to get more functional questions by enabling more "domains" in your Houndify dashboard.
